global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'expensy-backend-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend-service.taco-expensy.svc.cluster.local:80']
