apiVersion: v1
kind: Secret
metadata:
  name: expensy-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb://root:example@mongo-service:27017/?authSource=admin"
  REDIS_PASSWORD: "someredispassword"
